server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/readonly
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: ToDoList-ReadOnly

#logging:
#  level:
#    root: DEBUG
#    org.apache.http: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka