server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/writeonly
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: ToDoList-WriteOnly


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

